-- 5. Extend Vendors Table
ALTER TABLE vendors
ADD COLUMN IF NOT EXISTS tax_id_type VARCHAR(20) DEFAULT 'GST',
ADD COLUMN IF NOT EXISTS state VARCHAR(100),
ADD COLUMN IF NOT EXISTS country VARCHAR(100) DEFAULT 'India',
ADD COLUMN IF NOT EXISTS pin_code VARCHAR(50),
ADD COLUMN IF NOT EXISTS contact_person VARCHAR(150);
